### ISSUE TITLE
Добавить в  файл READMe описание удаления веток

### ISSUE THREAD

**Issue by VladimirTialin** [GitDeepHomeWork3/git_deep_homework3#1]
1. Перейти по ссылке https://smartiqa.ru/courses/git/lesson-3#theory;
2. найти 7-й параграф  и ознакомиться.
3. Перейти в файл READMe.md
4. Добавить заголовок УДАЛЕНИЕ ВЕТОК В GIT.
5. Кратко описать команду удаления веток в Git.
6. Сохранить изменения и оправить pull requests

**Comment by aagura** [comment]
Задание выполнено
